# .github/workflows/publish-alpha.yml

name: Publish Alpha

on:
  push:
    branches:
      - develop

jobs:
  publish-alpha:
    name: Build and Publish Alpha to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check for changesets
        id: changesets
        run: |
          if pnpm changeset status --since=origin/develop | grep -q "No unreleased changesets found"; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create snapshot version and publish
        if: steps.changesets.outputs.no_changes == 'false'
        run: |
          pnpm changeset version --snapshot alpha
          pnpm --filter @nexus-mf/core build
          pnpm --filter @nexus-mf/core publish --tag alpha --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
